import { NextRequest, NextResponse } from "next/server";
import { getBrief } from "@/lib/backend";

function formatDecisionBriefMd(b: Record<string, unknown>): string {
  const lines: string[] = [];
  lines.push(`# ${b.title || b.headline}`);
  lines.push("");
  lines.push(`> ${b.headline}`);
  lines.push("");
  lines.push(`**Score:** ${(b.final_score as number)?.toFixed(3) || "N/A"}`);
  lines.push(`**Family:** ${b.candidate_family}`);
  lines.push(`**Chemistry:** ${b.chemistry || "N/A"}`);
  lines.push(`**Confidence:** ${b.confidence_tier}`);
  lines.push(`**Sidecar:** ${b.sidecar_gate_decision}`);
  lines.push(`**Review:** ${b.review_state}`);
  lines.push("");

  if (b.why_promising) {
    lines.push("## Why Promising");
    lines.push(b.why_promising as string);
    lines.push("");
  }

  if (b.fast_charge_summary) {
    lines.push("## Fast-Charge Behavior");
    lines.push(b.fast_charge_summary as string);
    if (b.fast_charge_retention !== null && b.fast_charge_retention !== undefined)
      lines.push(`- Retention: ${((b.fast_charge_retention as number) * 100).toFixed(1)}%`);
    if (b.resistance_growth_pct !== null && b.resistance_growth_pct !== undefined)
      lines.push(`- R Growth: ${(b.resistance_growth_pct as number).toFixed(1)}%`);
    lines.push("");
  }

  if (b.degradation_summary) {
    lines.push("## Degradation");
    lines.push(b.degradation_summary as string);
    lines.push("");
  }

  const caveats = b.caveats as string[] | undefined;
  if (caveats && caveats.length > 0) {
    lines.push("## Caveats");
    for (const c of caveats) lines.push(`- ${c}`);
    lines.push("");
  }

  if (b.recommended_next || b.recommended_action) {
    lines.push("## Recommended Next Step");
    lines.push((b.recommended_next as string) || (b.recommended_action as string));
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Brief ID: ${b.id} · Created: ${b.created_at}*`);
  return lines.join("\n");
}

function formatResearchBriefMd(b: Record<string, unknown>): string {
  const lines: string[] = [];
  lines.push(`# Research: ${b.headline}`);
  lines.push("");
  lines.push(`> ${b.summary}`);
  lines.push("");
  lines.push(`**Topic:** ${b.topic}`);
  lines.push(`**Domain:** ${b.domain}`);
  lines.push(`**Evidence Quality:** ${b.evidence_quality}`);
  lines.push(`**Review:** ${b.review_state || "awaiting_review"}`);
  lines.push("");

  const dirs = b.promising_directions as Array<Record<string, string>> | undefined;
  if (dirs && dirs.length > 0) {
    lines.push("## Promising Directions");
    for (const d of dirs) {
      lines.push(`### ${d.title} (${d.confidence})`);
      lines.push(d.description);
      lines.push(`*Rationale: ${d.rationale}*`);
      lines.push("");
    }
  }

  const rejected = b.rejected_directions as Array<Record<string, string>> | undefined;
  if (rejected && rejected.length > 0) {
    lines.push("## Rejected Directions");
    for (const d of rejected) {
      lines.push(`### ${d.title}`);
      lines.push(d.description);
      lines.push(`*Reason: ${d.reason}*`);
      lines.push("");
    }
  }

  if (b.recommended_next) {
    lines.push("## Recommended Next Step");
    lines.push(b.recommended_next as string);
    lines.push("");
  }

  const caveats = b.caveats as string[] | undefined;
  if (caveats && caveats.length > 0) {
    lines.push("## Caveats");
    for (const c of caveats) lines.push(`- ${c}`);
    lines.push("");
  }

  lines.push("## Provenance");
  const sources = b.grounding_sources as string[] | undefined;
  if (sources && sources.length > 0) {
    for (const s of sources) lines.push(`- ${s}`);
  } else {
    lines.push("- No structured engine data was available for grounding");
  }
  lines.push("");
  lines.push("*This brief was generated by AI (DeepSeek) grounded in available engine outputs. It should be reviewed before use in decisions.*");
  lines.push("");
  lines.push("---");
  lines.push(`*Brief ID: ${b.id} · Created: ${b.created_at}*`);
  return lines.join("\n");
}

function formatDiligenceBriefMd(b: Record<string, unknown>): string {
  const lines: string[] = [];
  lines.push(`# Due Diligence: ${b.headline}`);
  lines.push("");
  lines.push(`> ${b.summary}`);
  lines.push("");
  lines.push(`**Subject:** ${b.subject}`);
  lines.push(`**Focus Areas:** ${(b.focus_areas as string[])?.join(", ") || "general"}`);
  lines.push(`**Review:** ${b.review_state || "awaiting_review"}`);
  lines.push("");

  const signals = b.strongest_signals as Array<Record<string, string>> | undefined;
  if (signals && signals.length > 0) {
    lines.push("## Key Signals");
    for (const s of signals) {
      const icon = s.signal_type === "positive" ? "+" : s.signal_type === "negative" ? "-" : "~";
      lines.push(`- **[${icon}] ${s.title}:** ${s.description}`);
    }
    lines.push("");
  }

  const risks = b.risks as Array<Record<string, string>> | undefined;
  if (risks && risks.length > 0) {
    lines.push("## Risks");
    for (const r of risks) {
      lines.push(`- **${r.title}** (${r.severity}): ${r.description}`);
    }
    lines.push("");
  }

  const questions = b.open_questions as string[] | undefined;
  if (questions && questions.length > 0) {
    lines.push("## Open Questions");
    for (const q of questions) lines.push(`- ${q}`);
    lines.push("");
  }

  if (b.recommendation) {
    lines.push("## Recommendation");
    lines.push(b.recommendation as string);
    lines.push("");
  }

  if (b.confidence_note) {
    lines.push(`*Confidence Note: ${b.confidence_note}*`);
    lines.push("");
  }

  const caveats = b.caveats as string[] | undefined;
  if (caveats && caveats.length > 0) {
    lines.push("## Caveats");
    for (const c of caveats) lines.push(`- ${c}`);
    lines.push("");
  }

  lines.push("## Provenance");
  const sources = b.grounding_sources as string[] | undefined;
  if (sources && sources.length > 0) {
    for (const s of sources) lines.push(`- ${s}`);
  } else {
    lines.push("- No structured engine data was available for grounding");
  }
  lines.push("");
  lines.push("*This brief was generated by AI (DeepSeek) grounded in available engine outputs. It should be reviewed before use in decisions.*");
  lines.push("");
  lines.push("---");
  lines.push(`*Brief ID: ${b.id} · Created: ${b.created_at}*`);
  return lines.join("\n");
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const briefId = searchParams.get("id");
  const format = searchParams.get("format") || "markdown";

  if (!briefId) {
    return NextResponse.json({ error: "Missing id parameter" }, { status: 400 });
  }

  const brief = await getBrief(briefId);
  if (!brief) {
    return NextResponse.json({ error: "Brief not found" }, { status: 404 });
  }

  const briefType = (brief.brief_type as string) || "decision";

  let markdown: string;
  if (briefType === "research") {
    markdown = formatResearchBriefMd(brief);
  } else if (briefType === "diligence") {
    markdown = formatDiligenceBriefMd(brief);
  } else {
    markdown = formatDecisionBriefMd(brief);
  }

  if (format === "json") {
    return NextResponse.json({ brief, markdown });
  }

  // Return as downloadable markdown
  return new NextResponse(markdown, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${briefType}_brief_${briefId}.md"`,
    },
  });
}
